### ISSUE TITLE
Hey Tuncion, thanks for the repo!

### ISSUE THREAD

**Issue by s1nyx** [Tuncion/auto-update-fivem-artifact#2]
Hey @Tuncion,

I just wanted to express my gratitude for this repo. It saved me time and still does everytime i boot a server :)

Have a nice day!

**Comment by Tuncion** [comment]
Hey @s1nyx,

Thank you very much for your feedback ❤️, I am pleased that I was able to achieve my goal: To improve the process of updating Artifact.
